name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        # Build directory where build files will be generated
        build-dir: ${{ runner.workspace }}/build
        # CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)
        build-type: Release
        # C Compiler for toolchain
        parallel: 4
